### ISSUE TITLE
'NoneType' object has no attribute 'decode' on "connection push" w/o --mvip

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/solidfire-cli#12]
It's strange that `--mvip` isn't required (I suppose that's correct *only* if `-c` is provided?), but there are messages like these which say it is required (below). Anyway, if I have a connection established and then try to `push` another one without `--mvip`, I get this error.

* CentOS 7.3 

```
[root@localhost SolidFire]# sfcli connection push --mvip 1.1.1.1
Name:test
Username:
Password:

[root@localhost SolidFire]# sfcli connection push
Name: Test1
ERROR:element.cli.cli:Please provide the mvip. It is a required parameter.
Traceback (most recent call last):
  File "/bin/sfcli", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/element/cli/commands/cmd_connection.py", line 99, in push
    'username': "b'"+ctx.username.decode('utf-8')+"'",
AttributeError: 'NoneType' object has no attribute 'decode'

[root@localhost SolidFire]# sfcli connection push --mvip 1.1.1.1
Name: Test
Username:
Password:
[root@localhost SolidFire]# python -V
Python 2.7.5
[root@localhost SolidFire]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

# pip list | grep solidfire
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
solidfire-cli (1.4.0.339)
solidfire-sdk-python (1.4.0.271)
```

**Comment by ArielCHoffman** [comment]
The mvip isn't required for normal commands if you are using the default connection or if you specify a given connection. Ergo, it's optional. However, if you want to push a new connection, the mvip associated therewith is not optional because we need to establish the connection. In either case, the cli shouldn't be throwing a bunch of stuff like that. It should just exit after the first error. I just fixed that in the dev branch and it'll be in the next version of the cli.

**Comment by scaleoutsean** [comment]
This seems to have been fixed.
