### ISSUE TITLE
solidfire-cli exception on CentOS/RedHat 7

### ISSUE THREAD

**Issue by aldemira** [solidfire/solidfire-cli#26]
After installing solidfire-cli with pip I getting the exception below:

[root@centos72 ~]# sfcli
Traceback (most recent call last):
  File "/usr/bin/sfcli", line 7, in <module>
    from element.cli.cli import cli
  File "/usr/lib/python2.7/site-packages/element/cli/cli.py", line 20, in <module>
    HELP_STRING = """Welcome to the SolidFire Command Line Interface """ + pkg_resources.require("solidfire-cli")[0].version + """.
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 630, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (setuptools 0.9.8 (/usr/lib/python2.7/site-packages), Requirement.parse('setuptools>=19.2'))

**Comment by ahaid** [comment]
Can you run `pip list` and paste the results in here?

**Comment by aldemira** [comment]
Sure:

backports.ssl-match-hostname (3.4.0.2)
certifi (2018.1.18)
chardet (3.0.4)
click (6.7)
configobj (4.7.2)
configshell-fb (1.1.18)
decorator (3.4.0)
enum34 (1.1.6)
ethtool (0.8)
filelock (3.0.4)
future (0.16.0)
getpass2 (1.0.2)
idna (2.6)
iniparse (0.4)
iotop (0.6)
javapackages (1.0.0)
jsonpickle (0.9.6)
jsonpointer (1.9)
kitchen (1.1.1)
kmod (0.1)
langtable (0.0.31)
lxml (3.2.1)
Magic-file-extensions (0.2)
MySQL-python (1.2.3)
nose (1.3.0)
numpy (1.7.1)
pcp (1.0)
perf (0.1)
pip (8.1.2)
psycopg2 (2.5.1)
pycryptodome (3.4.11)
pycurl (7.19.0)
pygobject (3.14.0)
pygpgme (0.3)
pyliblzma (0.5.3)
pyparsing (1.5.6)
python-augeas (0.5.0)
python-dmidecode (3.10.13)
pyudev (0.15)
pyxattr (0.5.1)
requests (2.18.4)
rtslib-fb (2.1.57)
setuptools (0.9.8)
simplejson (3.13.2)
six (1.9.0)
slip (0.4.0)
slip.dbus (0.4.0)
solidfire-cli (1.5.0.29)
solidfire-sdk-python (1.5.0.87)
targetcli-fb (2.1.fb41)
urlgrabber (3.10)
urllib3 (1.22)
urwid (1.1.1)
virtualenv (1.10.1)
yum-langpacks (0.4.2)
yum-metadata-parser (1.1.4)

**Comment by Salmanius** [comment]
Hey aldemira, sorry for the really late response. In testing a few other things I came across this exact error in my own CentOS 7 VM. I suspect you are not using a virtualenv which is strongly recommended, but the fix is as follows.

    pip install --upgrade setuptools --user python
