### ISSUE TITLE
mNode 9.3:  No distributions at all found for solidfire-cli

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/solidfire-cli#5]
* SolidFire Element OS 9.3 (mNode)
* Python 2.7.3

```
admin@SF-A8AD:~$ source pythoncli/bin/activate
(pythoncli)admin@SF-A8AD:~$ pip install solidfire-cli
Downloading/unpacking solidfire-cli
  Could not find any downloads that satisfy the requirement solidfire-cli
No distributions at all found for solidfire-cli
Storing complete log in /home/admin/.pip/pip.log
(pythoncli)admin@SF-A8AD:~$
```
Detailed log:

```
(pythoncli)admin@SF-A8AD:~$ cat /home/admin/.pip/pip.log
------------------------------------------------------------
/home/admin/pythoncli/bin/pip run on Thu Aug  3 08:08:06 2017
Downloading/unpacking solidfire-cli

  Getting page http://pypi.python.org/simple/solidfire-cli
  URLs to search for versions for solidfire-cli:
  * http://pypi.python.org/simple/solidfire-cli/
  Getting page http://pypi.python.org/simple/solidfire-cli/
  Analyzing links from page https://pypi.python.org/simple/solidfire-cli/
    Skipping link https://pypi.python.org/packages/64/43/688336b7e01da1a643eb127cd2ea653e2679c120782ee2b25bb9b59dc09d/solidfire_cli-1.4.0.339-py2.py3-none-any.whl#md5=2d9379836fda5845f72fac1503743967 (from https://pypi.python.org/simple/solidfire-cli/); unknown archive format: .whl
  Could not find any downloads that satisfy the requirement solidfire-cli

No distributions at all found for solidfire-cli

Exception information:
Traceback (most recent call last):
  File "/home/admin/pythoncli/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/home/admin/pythoncli/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/admin/pythoncli/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 978, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/home/admin/pythoncli/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/index.py", line 157, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for solidfire-cli

```

**Comment by scaleoutsean** [comment]
Works fine on Debian 9.1 (kernel 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64) with Python 2 (2.7.13)

**Comment by ahaid** [comment]
The error in your log is `unknown archive format: .whl`. 

Check out this SO article and see if the steps in it help. https://stackoverflow.com/questions/20950295/pip-install-error-unknown-archive-format-whl

**Comment by scaleoutsean** [comment]
It's weird (and known, but I forgot about it) - mNode points to its own cached repo and doesn't use public repos. Also it didn't have pip or wheel installed (at least not the new mNode I installed).

This worked, but I'm sure there are other ways:

```
wget https://bootstrap.pypa.io/get-pip.py
sudo python get-pip.py
sudo pip install --upgrade requests # req'd to fix a SSL bug in requests
pip install solidfire-cli
```
