### ISSUE TITLE
ValueError: Incorrect ARC4 key length (3 bytes) on connection push

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/solidfire-cli#8]
```
solidfire-cli (1.4.0.339)
solidfire-sdk-python (1.4.0.271)
pycryptodome (3.4.6)
```

Got [this](https://github.com/Legrandin/pycryptodome/blob/master/lib/Crypto/Cipher/ARC4.py#L93) errror:

```
sfcli connection push --mvip 192.168.1.20
Name: cluster1
Username: admin
Password:
Traceback (most recent call last):
  File "/usr/local/bin/sfcli", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/element/cli/commands/cmd_connection.py", line 85, in push
    cli_utils.establish_connection(ctx)
  File "/usr/local/lib/python3.5/dist-packages/element/cli/utils.py", line 191, in establish_connection
    'username': "b'"+encrypt(ctx.username).decode('utf-8')+"'",
  File "/usr/local/lib/python3.5/dist-packages/element/cli/utils.py", line 342, in encrypt
    cipher = ARC4.new(socket.gethostname().encode('utf-8'))
  File "/usr/local/lib/python3.5/dist-packages/Crypto/Cipher/ARC4.py", line 174, in new
    return ARC4Cipher(key, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/Crypto/Cipher/ARC4.py", line 95, in __init__
    len(key))
ValueError: Incorrect ARC4 key length (3 bytes)
$ locale
LANG=en_US.utf8
LANGUAGE=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

```

**Comment by ArielCHoffman** [comment]
Hi Sean,

This is a bug in the CLI. It is caused by the fact that your machine name is 3 bytes. We are trying to decide whether to release a hotfix for this or not. As a workaround, you can make your machine name 5 bytes or longer. This issue will definitely be fixed in the next version of the CLI which is about 2.5 months away. Thank you for noticing this issue! It is also fixed on the develop branch of this github if you want a fix right away.

Ariel

**Comment by scaleoutsean** [comment]
I see... I was fiddling around with connection name and UTF8 locales thinking it's about the length of one of the arguments. No wonder I couldn't duplicate this on in default mNode VM.

**Comment by scaleoutsean** [comment]
Using the latest releases, I can't repro this issue.

* solidfire-cli (1.5.0.29)
* solidfire-sdk-python (1.5.0.87)
