### ISSUE TITLE
ImportError: No module named 'element.cli' on Oracle Linux 7 (python 3.4)

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/solidfire-cli#9]
First I install some deps (python34-pip, python34-devel), then pip3 install (no virtualenv).

```
Running transaction
  Installing : python34-3.4.5-4.el7.x86_64                                                                                   1/8
  Installing : python34-libs-3.4.5-4.el7.x86_64                                                                              2/8
  Installing : python34-setuptools-19.2-3.el7.noarch                                                                         3/8
  Installing : python-srpm-macros-3-17.el7.noarch                                                                            4/8
  Installing : python-rpm-macros-3-17.el7.noarch                                                                             5/8
  Installing : python3-rpm-macros-3-17.el7.noarch                                                                            6/8
  Installing : python34-devel-3.4.5-4.el7.x86_64                                                                             7/8
  Installing : python34-pip-8.1.2-5.el7.noarch                                                                               8/8
  Verifying  : python34-setuptools-19.2-3.el7.noarch                                                                         1/8
  Verifying  : python34-devel-3.4.5-4.el7.x86_64                                                                             2/8
  Verifying  : python3-rpm-macros-3-17.el7.noarch                                                                            3/8
  Verifying  : python34-pip-8.1.2-5.el7.noarch                                                                               4/8
  Verifying  : python34-libs-3.4.5-4.el7.x86_64                                                                              5/8
  Verifying  : python-srpm-macros-3-17.el7.noarch                                                                            6/8
  Verifying  : python-rpm-macros-3-17.el7.noarch                                                                             7/8
  Verifying  : python34-3.4.5-4.el7.x86_64                                                                                   8/8

Installed:
  python34-devel.x86_64 0:3.4.5-4.el7                              python34-pip.noarch 0:8.1.2-5.el7

Dependency Installed:
  python-rpm-macros.noarch 0:3-17.el7      python-srpm-macros.noarch 0:3-17.el7      python3-rpm-macros.noarch 0:3-17.el7
  python34.x86_64 0:3.4.5-4.el7            python34-libs.x86_64 0:3.4.5-4.el7        python34-setuptools.noarch 0:19.2-3.el7

Complete!
$ sudo pip3 install solidfire-cli
Collecting solidfire-cli
  Downloading solidfire_cli-1.4.0.339-py2.py3-none-any.whl (101kB)
    100% |████████████████████████████████| 102kB 528kB/s
Collecting click>=5 (from solidfire-cli)
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 221kB/s
Collecting pycryptodome>=2.6.1 (from solidfire-cli)
  Downloading pycryptodome-3.4.6.tar.gz (6.5MB)
    100% |████████████████████████████████| 6.5MB 58kB/s
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python3.4/site-packages (from solidfire-cli)
Collecting future (from solidfire-cli)
  Downloading future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 92kB/s
Collecting getpass2 (from solidfire-cli)
  Downloading getpass2-1.0.2.zip
Collecting jsonpickle>=0.9.3 (from solidfire-cli)
  Downloading jsonpickle-0.9.5.tar.gz (65kB)
    100% |████████████████████████████████| 71kB 103kB/s
Collecting FileLock (from solidfire-cli)
  Downloading filelock-2.0.11.tar.gz
Collecting solidfire-sdk-python>=1.2 (from solidfire-cli)
  Downloading solidfire_sdk_python-1.4.0.271-py2.py3-none-any.whl (159kB)
    100% |████████████████████████████████| 163kB 72kB/s
Collecting simplejson (from solidfire-cli)
  Downloading simplejson-3.11.1.tar.gz (78kB)
    100% |████████████████████████████████| 81kB 64kB/s
Collecting requests>=2.9.1 (from solidfire-sdk-python>=1.2->solidfire-cli)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 100kB/s
Collecting enum34>=1.1.6 (from solidfire-sdk-python>=1.2->solidfire-cli)
  Downloading enum34-1.1.6-py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.9.1->solidfire-sdk-python>=1.2->solidfire-cli)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 92kB/s
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.9.1->solidfire-sdk-python>=1.2->solidfire-cli)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 71kB/s
Collecting idna<2.7,>=2.5 (from requests>=2.9.1->solidfire-sdk-python>=1.2->solidfire-cli)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 100kB/s
Collecting certifi>=2017.4.17 (from requests>=2.9.1->solidfire-sdk-python>=1.2->solidfire-cli)
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)
    100% |████████████████████████████████| 358kB 66kB/s
Installing collected packages: click, pycryptodome, future, getpass2, jsonpickle, FileLock, chardet, urllib3, idna, certifi, requests, enum34, solidfire-sdk-python, simplejson, solidfire-cli
  Running setup.py install for pycryptodome ... done
  Running setup.py install for future ... done
  Running setup.py install for getpass2 ... done
  Running setup.py install for jsonpickle ... done
  Running setup.py install for FileLock ... done
  Running setup.py install for simplejson ... done
Successfully installed FileLock-2.0.11 certifi-2017.7.27.1 chardet-3.0.4 click-6.7 enum34-1.1.6 future-0.16.0 getpass2-1.0.2 idna-2.6 jsonpickle-0.9.5 pycryptodome-3.4.6 requests-2.18.4 simplejson-3.11.1 solidfire-cli-1.4.0.339 solidfire-sdk-python-1.4.0.271 urllib3-1.22
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

$ sfcli connection push
Traceback (most recent call last):
  File "/usr/bin/sfcli", line 7, in <module>
    from element.cli.cli import cli
ImportError: No module named 'element.cli'

```
This is Oracle Linux 7.

```
$ sfcli --help
Traceback (most recent call last):
  File "/usr/bin/sfcli", line 7, in <module>
    from element.cli.cli import cli
ImportError: No module named 'element.cli'
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.4 (Maipo)
$ uname -a
Linux oraclelinux7 4.1.12-94.3.9.el7uek.x86_64 #2 SMP Fri Jul 14 20:09:40 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
$ python3 -V
Python 3.4.5
$ pip3 list
certifi (2017.7.27.1)
chardet (3.0.4)
click (6.7)
enum34 (1.1.6)
filelock (2.0.11)
future (0.16.0)
getpass2 (1.0.2)
idna (2.6)
jsonpickle (0.9.5)
pip (8.1.2)
pycryptodome (3.4.6)
requests (2.18.4)
setuptools (19.2)
simplejson (3.11.1)
solidfire-cli (1.4.0.339)
solidfire-sdk-python (1.4.0.271)
urllib3 (1.22)
```

If I change to root account, then sfcli works. 

I'll also try with python 2.7 later.

**Comment by scaleoutsean** [comment]
Apparently "real" RHEL (and CentOS) don't even have Python 3, so this must be one of little "issues" that can be attributed to Oracle's attempt to provide it. Closing as "invalid".
